import { ProjectDetails } from "./types";

const projectDatas: ProjectDetails[] = [
  {
    id: 1,
    title: "Ocean",
    description: "I love this work so much, so proud to be involve in this project.",
    time: "2021",
    img: "/images/TEST_JPG.jpg",
    gif: "/images/GIF/TEST_GIF.gif",
    longImg: "/images/TEST_JPG.jpg",
    longDescription: "This is where description goes to. Try to type more values in here to make it looks good. Try to type more word but still fit. Exactly what am I talking about is a mystery 1.",
    brainStormingDescription: "explaining what I am doing to people who know and try to make it look easy 1.",
    makingDescription: "making is where magic happened 1.",
    outComeDescription: "appreciate for any help 1.",
    brainStormingImg: ["bg-red-100", "bg-red-200", "bg-red-300"],
    makingImg: "bg-red-200",
    outComeImg: "bg-red-100",
    videoImg: "/images/TEST_YOUTUBE.jpg",
    videoUrl: "https://www.youtube.com/watch?v=vEhD5WwCo44",
    demoUrl: "/",
  },
  {
    id: 2,
    title: "Simple Twitter",
    description: "Surely teach me how to write code.",
    time: "2023",
    img: "/images/TEST2_JPG.jpg",
    gif: "/images/GIF/TEST_GIF.gif",
    longImg: "/images/TEST2_JPG.jpg",
    longDescription: "This is where description goes to. Try to type more values in here to make it looks good. Try to type more word but still fit. Exactly what am I talking about is a mystery 2.",
    brainStormingDescription: "explaining what I am doing to people who know and try to make it look easy 2.",
    makingDescription: "making is where magic happened 2.",
    outComeDescription: "appreciate for any help 2.",
    brainStormingImg: ["bg-red-100", "bg-red-200", "bg-red-300"],
    makingImg: "bg-red-200",
    outComeImg: "bg-red-100",
    videoImg: "/images/TEST2_YOUTUBE.jpg",
    videoUrl: "https://www.youtube.com/watch?v=vEhD5WwCo44",
    demoUrl: "/",
  },
  {
    id: 3,
    title: "LaBar game",
    description: "A little project that I joint.",
    time: "2024",
    img: "/images/TEST3_JPG.jpg",
    gif: "/images/GIF/TEST_GIF.gif",
    longImg: "/images/TEST3_JPG.jpg",
    longDescription: "This is where description goes to. Try to type more values in here to make it looks good. Try to type more word but still fit. Exactly what am I talking about is a mystery 3.",
    brainStormingDescription: "explaining what I am doing to people who know and try to make it look easy 3.",
    makingDescription: "making is where magic happened 3.",
    outComeDescription: "appreciate for any help 3.",
    brainStormingImg: ["bg-red-100", "bg-red-200", "bg-red-300"],
    makingImg: "bg-red-200",
    outComeImg: "bg-red-100",
    videoImg: "/images/TEST3_YOUTUBE.jpg",
    videoUrl: "https://www.youtube.com/watch?v=vEhD5WwCo44",
    demoUrl: "/",
  },
  {
    id: 4,
    title: "Sizing Kit Store Location",
    description: "Small little project.",
    time: "2024",
    img: "/images/TEST4_JPG.jpg",
    gif: "/images/GIF/TEST_GIF.gif",
    longImg: "/images/TEST4_JPG.jpg",
    longDescription: "This is where description goes to. Try to type more values in here to make it looks good. Try to type more word but still fit. Exactly what am I talking about is a mystery 4.",
    brainStormingDescription: "explaining what I am doing to people who know and try to make it look easy 4.",
    makingDescription: "making is where magic happened 4.",
    outComeDescription: "appreciate for any help 4.",
    brainStormingImg: ["bg-red-100", "bg-red-200", "bg-red-300"],
    makingImg: "bg-red-200",
    outComeImg: "bg-red-100",
    videoImg: "/images/TEST4_YOUTUBE.jpg",
    videoUrl: "https://www.youtube.com/watch?v=vEhD5WwCo44",
    demoUrl: "/",
  },
  {
    id: 5,
    title: "Chill split",
    description: "This is my fifth work, I truly admire the people who work with me in this project.",
    time: "2024",
    img: "/images/TEST5_JPG.jpg",
    gif: "/images/GIF/TEST_GIF.gif",
    longImg: "/images/TEST5_JPG.jpg",
    longDescription: "This is where description goes to. Try to type more values in here to make it looks good. Try to type more word but still fit. Exactly what am I talking about is a mystery 5.",
    brainStormingDescription: "explaining what I am doing to people who know and try to make it look easy 5.",
    makingDescription: "making is where magic happened 5.",
    outComeDescription: "appreciate for any help 5.",
    brainStormingImg: ["bg-red-100", "bg-red-200", "bg-red-300"],
    makingImg: "bg-red-200",
    outComeImg: "bg-red-100",
    videoImg: "/images/TEST5_YOUTUBE.jpg",
    videoUrl: "https://www.youtube.com/watch?v=vEhD5WwCo44",
    demoUrl: "https://cost-sharing-app-git-staging-samchlius-projects.vercel.app/",
  },
];

projectDatas.reverse();

export { projectDatas };